##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################


compute_host: yujunz-doctor-dev
compute_ip: 192.168.1.32
inspector_type: sample
inspector_port: 12345
consumer_ip: 192.168.1.45
consumer_port: 12346

doctor_project: doctor
doctor_user: doctor
doctor_pass: doctor
doctor_role: _member_
doctor_domain: Default
doctor_network: doctor
doctor_subnet: doctor
doctor_cidr: "192.168.168.0/24"
doctor_auth:
  username: "{{ doctor_user }}"
  password: "{{ doctor_pass }}"
  project_name: "{{ doctor_project }}"
doctor_server_count: 4

doctor_alarm_action: 'http://{{ consumer_ip }}:{{ consumer_port }}/failure'

doctor_monitor: 'python ../doctor/tests/monitor.py {{ compute_host }} {{ compute_ip }} {{ inspector_type }} >logs/monitor.log 2>&1 &'
doctor_inspector: 'python ../doctor/tests/inspector.py {{ inspector_port }}  >logs/inspector.log 2>&1 &'
doctor_consumer: 'python ../doctor/tests/consumer.py {{ consumer_port }} >logs/consumer.log 2>&1 &'
