##############################################################################
# Copyright (c) 2017 ZTE Corporation and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

---
- hosts: localhost

  gather_facts: no

  tasks:

  # Reverse order of setup

  - name: collecting doctor server facts
    os_server_facts:
      auth: "{{ doctor_auth }}"

  - name: deleting doctor alarms
    command: aodh alarm delete --name "doctor-{{ item }}"
    with_items:  "{{ openstack_servers|map(attribute='id')|list }}"

  - name: deleting doctor servers
    os_server:
      auth: "{{ doctor_auth }}"
      name: "{{ item }}"
      state: absent
    with_sequence: start=1 end={{ doctor_server_count|int }} format=doctor-%d
    async: 1800
    poll: 0
    register: doctor_servers

  - name: waiting for doctor servers to be removed
    async_status: jid={{ item.ansible_job_id }}
    register: doctor_jobs
    until: doctor_jobs.finished
    retries: 300
    with_items: "{{ doctor_servers.results }}"

  - name: deleting doctor subnet
    os_subnet:
      auth: "{{ doctor_auth }}"
      name: "{{ doctor_subnet }}"
      state: absent

  - name: deleting doctor network
    os_network:
      auth: "{{ doctor_auth }}"
      name: "{{ doctor_network }}"
      state: absent

  - name: deleting doctor user
    os_user:
      name: "{{ doctor_user }}"
      state: absent

  - name: deleting doctor project
    os_project:
      name: "{{ doctor_project }}"
      state: absent
